name: Docker Image CI

on:
  workflow_dispatch:
  release:
    types: [released,prereleased]

jobs:

  build_latest:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease == false }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image (latest)
      run: docker build . --file Dockerfile --tag ${{ github.repository }}:latest
  
  build_dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease == true }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image (dev)
      run: docker build . --file Dockerfile --tag ${{ github.repository }}:dev
