name: Build and push Docker image to AWS ECR on shared-services

on:
  workflow_call:
    inputs:
      trigger_latest:
        type: boolean
        default: false
        required: false
      cdn_url:
        type: string
        default: 'https://cdn.docrevolution.nl/files'
        required: false
      cdn_url_dev:
        type: string
        default: 'https://uploads.my-test.docrevolution.com/assets'
        required: false
    secrets:
      AWS_REGION_SHARED_SERVICES:
        required: true
      AWS_ACCESS_KEY_ID_SHARED_SERVICES:
        required: true
      AWS_SECRET_ACCESS_KEY_SHARED_SERVICES:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tag: latest
            condition: ${{ inputs.trigger_latest == true || (github.event_name == 'release' && github.event.release.prerelease == false && !contains(github.event.release.tag_name, '-BETA')) }}
            image_tag: latest
            cdn_url: ${{ inputs.cdn_url }}
          - tag: dev
            condition: ${{ github.event.release.prerelease == true && contains(github.event.release.tag_name, '-BETA') }}
            image_tag: dev
            cdn_url: ${{ inputs.cdn_url_dev }}
          - tag: pre-release
            condition: ${{ github.event.release.prerelease == true && contains(github.event.release.tag_name, '-RC') }}
            image_tag: pre-release
            cdn_url: ${{ inputs.cdn_url }}
    if: ${{ matrix.condition }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.10.0

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-region: ${{ secrets.AWS_REGION_SHARED_SERVICES }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_SHARED_SERVICES }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_SHARED_SERVICES }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ matrix.image_tag }}
          cache-from: type=registry,ref=${{ steps.login-ecr.outputs.registry }}/${{ github.event.repository.name }}:${{ matrix.image_tag }}
          cache-to: type=inline
          build-args: |
            CDN_URL=${{ matrix.cdn_url }}
