name: Docker Image CI

on:
  release:
    types: [released,prereleased]

jobs:
  build_latest:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease == false }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image (latest)
      run: docker build . --file Dockerfile --tag ${{ github.event.repository.name }}:latest --tag ${{ github.event.repository.name }}:${{ github.event.release.tag_name }}
  
  build_dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease == true }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image (dev)
      run: docker build . --file Dockerfile --tag ${{ github.event.repository.name }}:dev --tag ${{ github.event.repository.name }}:${{ github.event.release.tag_name }}
