name: Docker Image CI

on:
  release:
    types: [released,prereleased]
  workflow_call:
    outputs:
      registry:
        description: "ECR registry"
        value: ${{ jobs.configure_ecr.outputs.registry }}

jobs:
  configure_ecr:
    runs-on: ubuntu-latest
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-west-1
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

  build_latest:
    needs: configure_ecr
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease == false }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build the Docker image (latest)
      env:
        REGISTRY: ${{ needs.configure_ecr.outputs.registry }}
        REPOSITORY: ${{ github.event.repository.name }}
        TAG: ${{ github.event.release.tag_name }}
      run: |
        docker build . --file Dockerfile --tag $REGISTRY/$REPOSITORY:latest --tag $REGISTRY/$REPOSITORY:$TAG
        docker image push --all-tags $REGISTRY/$REPOSITORY

  build_dev:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease == true && contains(github.event.release.tag_name, '-BETA') }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image (dev)
      run: docker build . --file Dockerfile --tag ${{ github.event.repository.full_name }}:dev --tag ${{ github.event.repository.full_name }}:${{ github.event.release.tag_name }}

  build_pre_release:
    runs-on: ubuntu-latest
    if: ${{ github.event.release.prerelease == true && contains(github.event.release.tag_name, '-RC') }}
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image (pre-release)
      run: docker build . --file Dockerfile --tag ${{ github.event.repository.full_name }}:pre-release --tag ${{ github.event.repository.full_name }}:${{ github.event.release.tag_name }}
